---
- hosts: bastion
  remote_user: ubuntu
  sudo: yes

  tasks:
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=86400

  - name: Install system packages for Ansible
    apt: name={{ item }} state=present
    with_items:
      - python-dev
      - python-pip

  - name: Install Ansible
    pip: name=ansible

  - name: Copy Ansible vars
    copy: src={{ item }} dest=/home/ubuntu owner=ubuntu group=ubuntu
    with_items:
      - group_vars
      - host_vars

  - name: Copy Ansible files
    copy: src={{ item }} dest=/home/ubuntu/{{ item }} owner=ubuntu group=ubuntu
    with_items:
      - provision_consul.yaml
      - hosts

  - name: Copy folders
    copy: src={{ item }} dest=/home/ubuntu owner=ubuntu group=ubuntu
    with_items:
      - files
      - templates

  - name: Make hosts executable
    file: path=/home/ubuntu/hosts mode=0755

